title: Warda
logo: https://username.github.io/repository/assets/images/profil_image.jpg

show_downloads: True
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme 
<img src="/assets/images/profil_image.jpg" alt="Logo de Warda" />

gem "github-pages", group: :jekyll_plugins
